module.exports = [
  "AddressUpgradeable.sol",
  "ContextUpgradeable.sol",
  "IDEXFactory.sol",
  "IDEXPair.sol",
  "IDEXRouter.sol",
  "IERC20MetadataUpgradeable.sol",
  "IERC20Upgradeable.sol",
  "INEFTiPEDiAToken.sol",
  "Initializable.sol",
  "IPinkAntiBot.sol",
  "NEFTiPEDiA.sol",
  "OwnableUpgradeable.sol",
  "ReentrancyGuardUpgradeable.sol",
  "SafeMath.sol",
]
